language: node_js
node_js:
  - 5.7

cache:
  directories:
    - node_modules

services:
  - mongodb
addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server

script:
  - npm run lint
  - npm test
