language: node_js
node_js:
  - 6.1

cache:
  - apt
  - directories:
    - node_modules
    - $NVM_DIR

services:
  - mongodb
addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server

script:
  - npm run lint
  - npm run test
