language: node_js
node_js:
  - 7.0.0

cache:
  - apt
  - directories:
    - node_modules
    - $NVM_DIR

services:
  - mongodb
addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server

script:
  - mongod --version
  - npm run lint
  - npm run test
